  default: &default
    adapter: postgresql
    encoding: unicode
    user: postgres
    password: Jones102030
    host: jones.c71i5des00ix.ca-central-1.rds.amazonaws.com
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

  development:
    <<: *default
    database: ecommerce_api_development

  test:
    <<: *default
    database: ecommerce_api_test
  production:
    <<: *default
    database: ecommerce_api_production

